import { useState } from 'react';

const API_URL = import.meta.env.VITE_API_BASE_URL ? `${import.meta.env.VITE_API_BASE_URL}/api/insights` : '/api/insights';

export default function InsightsPanel({ query }: { query: string }) {
  const [insight, setInsight] = useState('OpenAI insights are generated by the Cloudflare Worker when OPENAI_API_KEY is configured server-side.');
  const [status, setStatus] = useState<'idle' | 'loading' | 'error'>('idle');

  async function requestInsight() {
    setStatus('loading');
    try {
      const response = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query }) });
      const payload = await response.json() as { insight?: string; error?: string };
      if (!response.ok || !payload.insight) throw new Error(payload.error ?? 'Unable to fetch insight.');
      setInsight(payload.insight);
      setStatus('idle');
    } catch (error) {
      setStatus('error');
      setInsight(error instanceof Error ? error.message : 'Unable to fetch insight.');
    }
  }

  return (
    <div className="insight-box">
      <button className="button" type="button" onClick={requestInsight} disabled={status === 'loading' || query.trim().length < 4}>{status === 'loading' ? 'Generating…' : 'Generate insight'}</button>
      <p role={status === 'error' ? 'alert' : 'status'}>{insight}</p>
    </div>
  );
}
